# Generated by Django 4.1.5 on 2023-08-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativity_overflow', '0004_art_status_alter_art_artist_alter_inventory_artist_and_more'),
        ('accounts', '0003_artist_customuser_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
