# Generated by Django 4.1.5 on 2023-08-05 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_artist_customuser_credits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creativity_overflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('bidders', models.JSONField(default=dict)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('category', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_artworks', to=settings.AUTH_USER_MODEL)),
                ('highest_bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidded_on_artworks', to='accounts.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('catogry', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('bidders', models.JSONField(default=dict)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=18)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('category', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_artworks', to=settings.AUTH_USER_MODEL)),
                ('highest_bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidded_on_sold_artworks', to='accounts.customuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Thing',
        ),
    ]
