# Generated by Django 4.1.5 on 2023-08-05 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_artist_customuser_credits'),
        ('creativity_overflow', '0002_art_inventory_sold_delete_thing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='catogry',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='art',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_artworks', to='accounts.artist'),
        ),
        migrations.AlterField(
            model_name='art',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidded_on_artworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.artist'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_artworks', to='accounts.artist'),
        ),
    ]
