# Generated by Django 4.1.5 on 2023-08-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativity_overflow', '0004_art_status_alter_art_artist_alter_inventory_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='bidders',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
