# Generated by Django 4.1.5 on 2023-08-08 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creativity_overflow', '0005_alter_art_bidders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidded_on_artworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
