# Generated by Django 4.1.5 on 2023-08-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativity_overflow', '0006_alter_art_highest_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
