# Generated by Django 4.1.5 on 2023-08-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativity_overflow', '0008_alter_art_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
