# Generated by Django 4.1.5 on 2023-08-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativity_overflow', '0010_alter_art_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='category',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved')], default='physical_art', max_length=30),
        ),
    ]
