# Generated by Django 4.1.5 on 2023-08-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativity_overflow', '0011_alter_art_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='category',
            field=models.CharField(choices=[('physical_art', 'Physical Art'), ('digital_art', 'Digital Art'), ('photography', 'Photography')], default='physical_art', max_length=30),
        ),
    ]
