# Generated by Django 4.1.5 on 2023-08-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creativity_overflow', '0012_alter_art_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved')], max_length=10),
        ),
    ]
